# Generated by Django 4.0b1 on 2021-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify_rest_framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
